# Default config file for Hexchanting

# If deleted this file will be regenerated on next launch.
# If this file cannot be loaded then default values will be used.
# If this file can be loaded but is invalid then loading will be halted and the game will crash.
# This is probably an error with your config, but if you are sure it isn't please open a bug.
# https://github.com/arconyx/hexchanting/issues

# Notes
# Boolean values accept 'true' or 'false' (no quotes).

# Current config version. Don't touch this and don't remove it.
# Valid values: integer (default 1)
version = 1

# Control when the chestplate hex triggers during damage processing. This changes what hex designs are viable.
# Changing this setting in an existing world is technically safe, but it will change behaviour that your hexes may
# rely on!
# When 'true' the chestplate trigger fires after damage is applied to the player.
# The damage value provided to the hex has armour, enchantments and absorption applied.
# If 'false' then the trigger fires before damage is applied to the player and does not
# factor in any of the above modifiers. This is the behaviour in Hexchanting versions <1.2,
# prior to this option being added.
#
# Valid values: boolean (default false)
applyDamageBeforeChestplateTrigger = false