#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 27 21:46:15 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
