#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 07 10:49:43 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
