#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 23 18:35:24 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
