#Which item activates the Blueprint selection tool.
#Set to a different item (e.g. 'create:schematic_and_quill') to piggyback on it.
#When set to anything other than 'ponderer:blueprint', or when Create is loaded,
#the built-in Blueprint item will not appear in the creative tab.
blueprintCarrierItem = "minecraft:paper"

